### ISSUE TITLE
Create nuget package

### ISSUE THREAD

**Issue by dzmitry-lahoda** [sailro/Shellify#1]
I use COM to automate deployment of software which needs to create lnk. I use nuget to fetch all dependencies for F# scripts which do this. I'd like to avoid any COM access and use you api instead.

**Comment by sailro** [comment]
Since Stuxnet LNK vulnerability, Microsoft changed the way of creating .lnk files and Shellify is -at this time- only able to alter files.

**Comment by dzmitry-lahoda** [comment]
I see. And there is another new patch for previous patch https://threatpost.com/patched-windows-machines-exposed-to-stuxnet-lnk-flaw-all-along/111558 ))
